site_name: Project Docs
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - plantuml_markdown

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
  - mermaid2

strict: true
