name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: uv pip install -e .[dev]
      - run: make lint test

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: uv pip install -e .[dev]
      - run: mkdocs build --strict
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site/

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: uv pip install -e .[dev]
      - run: bandit -r src

  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dependabot/fetch-metadata@v1
      - run: dependabot update

  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: uv pip install -e .[dev]
      - run: yamlfmt
      - run: locust -f tests/performance/locustfile.py
