name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          uv pip install -e .[dev]

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1
        with:
          package-ecosystem: "pip"
          directory: "/"
          schedule-interval: "weekly"
